### ISSUE TITLE
OpenFOAM 2.3.1

### ISSUE THREAD

**Issue by sanguinariojoe** [phicau/IHFOAM#3]
ihFoam solver is not compiling in OpenFOAM 2.3.1 because alphaOuterCorrectors variable has been removed (solvers/ihFoamOF230/ihFoam.C & solvers/ihFoamOF230/ihDyMFoam/ihDyMFoam.C). More info here:

http://www.openfoam.org/mantisbt/view.php?id=1225

And a patch to fix it here:

https://github.com/OpenFOAM/OpenFOAM-2.3.x/commit/3c837948f19c4f21570201595ac7396809f308ef

P.S. I tested it and works fine!

**Comment by phicau** [comment]
Thanks a lot Jose, I will update the sources when I find some time.

Best,

Pablo

**Comment by meouda** [comment]
Dears Sanguinariojoe and Phicau,

I am trying to compile the IHFOAM Solvers for OpenFoam 2.3.1 but I get the following error message:

ouda@ouda-VirtualBox:~/IHFOAM/solvers/ihFoamOF230$ ./allMake
Making dependency list for source file ihFoam.C
SOURCE=ihFoam.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -ggdb3 -I/opt/openfoam231/src/transportModels/twoPhaseMixture/lnInclude -I/opt/openfoam231/src/transportModels -I/opt/openfoam231/src/transportModels/incompressible/lnInclude -I/opt/openfoam231/src/transportModels/interfaceProperties/lnInclude -I/opt/openfoam231/src/turbulenceModels/incompressible/turbulenceModel -I/opt/openfoam231/src/finiteVolume/lnInclude -I/opt/openfoam231/src/meshTools/lnInclude -I/opt/openfoam231/src/fvOptions/lnInclude -I/opt/openfoam231/src/sampling/lnInclude -IlnInclude -I. -I/opt/openfoam231/src/OpenFOAM/lnInclude -I/opt/openfoam231/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/ihFoam.o
ihFoam.C: In function ‘int main(int, char**)’:
ihFoam.C:112:39: error: ‘alphaOuterCorrectors’ was not declared in this scope
             if (pimple.firstIter() || alphaOuterCorrectors)
                                       ^
In file included from ihFoam.C:86:0:
/opt/openfoam231/src/finiteVolume/lnInclude/readTimeControls.H:38:8: warning: unused variable ‘maxDeltaT’ [-Wunused-variable]
 scalar maxDeltaT =
        ^
make: *** [Make/linux64GccDPOpt/ihFoam.o] Error 1
ihFoam compilation failed

How to use your patch to solve this problem?

Please Help.

Best regards

**Comment by sanguinariojoe** [comment]
You just need to remove the if statement affected, for instance:

<pre><code>
if (pimple.firstIter() || alphaOuterCorrectors)
{
    twoPhaseProperties.correct();

    #define LTSSOLVE
    #include "alphaEqnSubCycle.H"
    #undef LTSSOLVE
}
</code></pre>

should be replaced by:

<pre><code>
twoPhaseProperties.correct();

#define LTSSOLVE
#include "alphaEqnSubCycle.H"
#undef LTSSOLVE
</code></pre>

Best regards,
Pepe
