### ISSUE TITLE
Tutorials?

### ISSUE THREAD

**Issue by petebachant** [phicau/IHFOAM#4]
The wiki page states there are tutorials available. Can you add them to this repo?

**Comment by phicau** [comment]
Hi Pete,

the tutorials can be accessed upon registration in:

http://ihfoam.ihcantabria.com/source-download/

Currently we are not considering adding them to GitHub because the statistics that the registration form provides are very useful.

Best,

Pablo

**Comment by phicau** [comment]
Hi Pete,

by popular request, the tutorials have been uploaded to this git repository.

Best regards,

Pablo
