### ISSUE TITLE
FOAM FATAL IO ERROR: Unknown patchField type IH_Waves_InletVelocity for patch type path 

### ISSUE THREAD

**Issue by arieledesess** [phicau/IHFOAM#5]
Hi, 

I'm just getting started with OpenFOAM and want to create a free surface. I found IHFOAM for this (thanks, by the way!!!) and thought I compiled it successfully (all wave boundary conditions and solvers compiled successfully) but I am trying to run the irreg45degtank tutorial and am getting the error:

<Unknown patchField type IH_Waves_InletVelocity for patch type patch> 

My guess is that something isn't linked properly but I'm not sure how to fix this... any ideas? Or let me know whatever other information you need me to give you..

Thanks again in advance and thanks for making this available! 

Ariel

**Comment by phicau** [comment]
Hi Ariel,

thanks! A couple of questions:
Which version are you using?
Did you make any changes?

From the error message I guess that there is a typo somewhere. I am not sure if it was me or you introducing it. Do you notice the last word "path"? 

FOAM FATAL IO ERROR: Unknown patchField type IH_Waves_InletVelocity for patch type path

It should be "patch" instead.

Let me know if this solves the problem or if it is still there.

Best,

Pablo

**Comment by arieledesess** [comment]
Hi Pablo, 

Thanks so much for getting back to me so quickly. First of all, I am on Ubuntu 12.04 running OpenFOAM 2.3.1. That typo was my fault, the typo isn't there in the error, so the error does have patch (not path).

I have not made any changes (to my knowledge!!)

At the end of the error, after the list of suggested patchField types is this: 

file: /home/ariel/FoamCases/irreg45degTank/0/U.boundaryField.inlet from line 26 to line 28.

    From function fvPatchField<Type>::New(const fvPatch&, const DimensionedField<Type, volMesh>&, const dictionary&)
    in file /home/ariel/OpenFOAM/OpenFOAM-2.3.1/src/finiteVolume/lnInclude/fvPatchFieldNew.C at line 143.

I'm not sure if that could be the problem? 

Let me know if there's any other information I can give you. 

Best regards, 
Ariel

**Comment by arieledesess** [comment]
Hi Pablo,

Quick question on this same error… is it because I’m using the “interFoam” command to run it? Should I be using another one? 

Best regards, 
Ariel 
_________________________________
Ariel Jane Edesess, B.Sc. M.Sc.

Ph.D. Researcher	
Civil and Environmental Engineering
University College Cork 
Marine Renewable Energy Ireland (MaREI)
EMAIL: a.edesess@umail.ucc.ie
PHONE: +353 (021) 490 3767
MOBILE: +353 (085) 146 4676

**Comment by phicau** [comment]
Hi Ariel,

definitely, you should use 'ihfoam' to run the case.

I have never used version 2.3.1, though. Probably you need to make some changes or even build your own ihfoam solver. See one of the other incidences reported here at GitHub. That is why I was unsure of this report, and needed to check additional details.

For a full compatibility list see: https://openfoamwiki.net/index.php/Contrib/IHFOAM#Supported_Versions

Best,

Pablo

**Comment by arieledesess** [comment]
Hi Pablo, 

Thank you for your email and again for getting back to me so quickly. Just had a quick try and using ‘ihfoam’ resulted in a ‘command not found’ error… Could this be an issue with using version 2.3.1? I might just download 2.3.0 anyway as it seems to be much  more widely used. 

Best regards, 
Ariel 
_________________________________
Ariel Jane Edesess, B.Sc. M.Sc.

Ph.D. Researcher	
Civil and Environmental Engineering
University College Cork 
Marine Renewable Energy Ireland (MaREI)
EMAIL: a.edesess@umail.ucc.ie
PHONE: +353 (021) 490 3767
MOBILE: +353 (085) 146 4676

**Comment by phicau** [comment]
Yes, the IHFOAM solver has not been compiled, that is why it is not found. Check this out: https://github.com/phicau/IHFOAM/issues/3

Probably the most convenient solution is to set up a supported version.

Best,

Pablo

**Comment by arieledesess** [comment]
Hi Pablo, 

I’m contacting you again about ihFoam, but this time it’s about the results from the irreg45degtank code. First of all, I made the mistake of running this on my laptop (I ran it in parallel but I only have 4 cores so I ran it on 2, it took about a week I think). I obviously should have run it to transfer data to an external hard drive but I didn’t so it took up most of my memory… well I’ve learned for next time! I am now trying to view the case using paraview but when I try to run it, the time only goes up to 1 (not 200) and it is not showing any changes. Do you have any experience with this or know why it would not run the entire simulation? I apologise if this is a very basic question but I am working on my own with OpenFOAM and CFD in general so do not fully understand what would make a simulation not run fully or not be displayed properly. Might this be due to a lack of memory? 

I appreciate your patience and look forward to hearing back from you. 

Best regards, 
Ariel 
_________________________________
Ariel Jane Edesess, B.Sc. M.Sc.

Ph.D. Researcher	
Civil and Environmental Engineering
University College Cork 
Marine Renewable Energy Ireland (MaREI)
EMAIL: a.edesess@umail.ucc.ie
PHONE: +353 (021) 490 3767
MOBILE: +353 (085) 146 4676

**Comment by phicau** [comment]
Hi Ariel,

paraview has an option to load decomposed cases, check it out.

I also suggest that we keep this space for bur reports. General issues can be treated in cfd-online.com, where more people will be able to help you.

Best regards,

Pablo
