### ISSUE TITLE
Another compilation issue

### ISSUE THREAD

**Issue by Antelox** [phicau/IHFOAM#6]
Hi to all,
I installed OpenFOAM 2.4.0 with apt-get in Xubuntu 14.04 (trusty). With OpenFOAM it's all ok and I'm able to run some basic simulations. But the issue is with IHFOAM compilation.

When I run 'sudo sh ./allMake' I get this:

allMake: line 3: [: ==: unary operator expected
allMake: line 11: wclean: command not found
allMake: line 13: wmake: command not found
\n\nWave generation boundary conditions compilation failed

How can I solve? I saw also another compilation issue reported before that now it's closed but I sincerly don't understand how he solved that.

Tnx in advance.

Antelox

**Comment by phicau** [comment]
Hi Antelox,

did you install OpenFOAM as root? Apparently not, since root does not know about wclean and wmake.

Please compile IHFOAM as your regular user './allMake' and it shall work. I just tested in a clean version of Xubuntu 14.04.3 and there are no problems.

Best,

Pablo
